#!/usr/bin/env bash
# This is the command you use to initiate an SSH connection.
# -i: This option is followed by the path to your private key file.
# ~/.ssh/school: This is the path to your private key file.
# ubuntu: This is the username you want to log in as on the remote server.
# @: The "@" symbol is used to separate the username from the hostname or IP address.
# 100.25.33.220: This is the hostname or IP address of the remote server you want to connect to.
.ssh/id_ed25519.pub
